name: rnaseq-workflow
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - snakemake-minimal>=7.32
  - fastqc>=0.12
  - fastp>=0.23
  - salmon>=1.10
  - multiqc>=1.21
  - pandas>=2.0
  - numpy>=1.26
  - pip
  - pyarrow>=15.0
  - pip:
      - pytximport>=0.9
